import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import { windowColor } from "@/colors/color";

// Correctly import Alegreya without redeclaring
const alegreya = Noto_Serif({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${alegreya.className} antialiased`}
        style={{ backgroundColor: windowColor, maxWidth: '100vw', overflowX: "hidden" }}
      >
        <main className=" bg-zinc-200 flex justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
